---
title: "Data extraction"
date: "22/10/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(syllable)
```

```{r get-database}
ipa <- read_csv("./arpabet2ipa.csv") %>%
    mutate(arpabet = tolower(arpabet))
pronounce <- read_csv("./pronounce.csv", col_names = c("word", "arpabet")) %>%
    distinct(word, .keep_all = TRUE) %>%
    mutate(
        word = tolower(word),
        arpabet = strsplit(as.character(arpabet), " ")
    ) %>%
    unnest() %>%
    left_join(y = ipa) %>%
    select(-arpabet) %>%
    group_by(word) %>%
    summarise(ipa = paste(ipa, collapse = ""), cv = paste(cv, collapse = ""))

subtlex <- read_tsv("http://crr.ugent.be/papers/SUBTLEX-UK.txt", trim_ws = T) %>%
    left_join(y = pronounce, by = c("Spelling" = "word"))
```

```{r filter}
target <- c("t", "p", "k")

cvc_ptk <- subtlex %>%
    filter(
        cv == "CVC",
        substring(
            ipa,
            nchar(ipa),
            nchar(ipa)
        ) %in% target,
        is.na(Homophonic_entry),
        substring(ipa, 1, 1) != 'h'
    )
```

The next chunk creates tibbles with word-final /t/, word-final /p/, and word-final /k/ words separately.

```{r filter}
cvc_t <- cvc_ptk %>% 
  filter(
    substring(ipa, nchar(ipa), nchar(ipa)) == 't'
    )
cvc_p <- cvc_ptk %>% 
  filter(
    substring(ipa, nchar(ipa), nchar(ipa)) == 'p'
    )
cvc_k <- cvc_ptk %>% 
  filter(
    substring(ipa, nchar(ipa), nchar(ipa)) == 'k'
    )
```
