---
title: "Contact Quotient analysis"
author: "Stefano Coretta and Massimiliano Canzi"
date: "13/01/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../"))
library(tidyverse)
theme_set(theme_minimal())
library(mgcv)
library(itsadug)
library(tidymv)
library(lmerTest)
library(effects)
```

# Read data

```{r read-data, message=FALSE}
words <- read_csv("./stimuli/words.csv")

cq <- read_csv("./results/tracegram.csv") %>%
  mutate(
    cq = minimum - maximum,
    position = ordered(position, levels = c("medial", "final"))
  ) %>%
  left_join(y = words) %>%
  mutate(
    freq_bin = ifelse(
      log_frequency < 4.465,
      "low",
      "high"
    ),
    vowel = as.ordered(vowel),
    consonant_2 = ordered(consonant_2, levels = c("k", "t")),
    cons_pos = interaction(consonant_2, position)
  ) %>%
  mutate_if(is.character, as.factor) %>%
  mutate(index = as.factor(index)) %>%
  filter(cq > 0, cq < 1)

contrasts(cq$position) <- "contr.treatment"
contrasts(cq$vowel) <- "contr.treatment"
contrasts(cq$consonant_2) <- "contr.treatment"
```

# Exploration

```{r cq-density}
cq %>%
  ggplot(aes(cq)) +
  geom_density()
```

```{r cq-density-speaker}
cq %>%
  ggplot(aes(cq)) +
  geom_density() +
  facet_grid(~ speaker)
```

m03 has a strong outlier peak around 0.2.

```{r cq-density-speaker}
cq %>%
  ggplot(aes(cq, fill = position)) +
  geom_density(alpha = 0.3) +
  facet_grid(~ speaker)
```

```{r cq-density-speaker}
cq %>%
  ggplot(aes(cq, fill = position)) +
  geom_density(alpha = 0.3) +
  facet_grid(consonant_2 ~ speaker) +
  geom_rug()
```

Outliers in m03 are especially from final /k/ and medial/final /t/.

```{r cq-position}
cq %>%
  ggplot(aes(proportion, cq, colour = position)) +
  geom_point(alpha = 0.2) +
  geom_smooth() +
  facet_wrap(~ speaker)
```

```{r cq-position-consonant}
cq %>%
  ggplot(aes(proportion, cq, colour = position)) +
  geom_point(alpha = 0.2) +
  geom_smooth() +
  facet_grid(speaker ~ consonant_2 )
```

```{r cq-position-consonant}
cq %>%
  filter(cq > 0.3) %>%
  ggplot(aes(proportion, cq, colour = position)) +
  geom_point(alpha = 0.2) +
  geom_smooth() +
  facet_grid(speaker ~ consonant_2 )
```

```{r cq-position-consonant-frequency}
cq %>%
  ggplot(aes(proportion, cq, colour = freq_bin)) +
  geom_point(alpha = 0.2) +
  geom_smooth() +
  facet_grid(speaker + position ~ consonant_2)
```

```{r cq-boxplot}
cq %>%
  ggplot(aes(freq_bin, cq)) +
  geom_boxplot() +
  facet_grid(position ~ consonant_2)
```

```{r}
cq %>%
  filter(proportion > 0.49, proportion < 0.51) %>%
  ggplot(aes(position, cq)) +
  geom_boxplot()
```

```{r}
cq %>%
  filter(proportion > 0.49, proportion < 0.51) %>%
  ggplot(aes(position, cq)) +
  geom_boxplot() +
  facet_grid(~ consonant_2)
```

```{r}
cq %>%
  filter(proportion > 0.49, proportion < 0.51, cq < 0.6) %>%
  ggplot(aes(position, cq)) +
  geom_boxplot() +
  facet_grid(~ consonant_2)
```

```{r}
filter(cq, speaker == "m03", position == "final") %>%
  ggplot(aes(proportion, cq, colour = vowel)) +
  geom_point() +
#  geom_smooth() +
  facet_grid(. ~ consonant_2)
```

```{r}
filter(cq, speaker == "m03", position == "final") %>%
  ggplot(aes(cq, fill = vowel)) +
  geom_density(alpha = 0.2) +
  facet_grid(. ~ consonant_2)
```

# GAM

```{r cq-gam}
cq_gam_2 <- bam(
  cq ~
    cons_pos +
    s(proportion) +
    s(proportion, by = cons_pos) +
    ti(proportion, log_frequency) +
    ti(proportion, log_frequency, by = cons_pos) +
    s(proportion, speaker, bs = "fs"),
  data = filter(cq, log_frequency > 3.5),
  method = "ML"
)

summary(cq_gam_2)
```

```{r cq-gam-plot}
fvisgam(
  cq_gam_2,
  view = c("proportion", "log_frequency"),
  cond = list(
    cons_pos = "t.medial"),
  rm.ranef = TRUE
)
fvisgam(
  cq_gam_2,
  view = c("proportion", "log_frequency"),
  cond = list(
    "t.final"),
  rm.ranef = TRUE
)
```

```{r cq-gam-plot}
fvisgam(
  cq_gam_2,
  view = c("proportion", "log_frequency"),
  cond = list(cons_pos = "k.medial"),
  rm.ranef = TRUE
)
fvisgam(
  cq_gam_2,
  view = c("proportion", "log_frequency"),
  cond = list(cons_pos = "k.final"),
  rm.ranef = TRUE
)
```


```{r}
plot_smooth(
  cq_gam_2,
  "proportion",
  cond = list(
    log_frequency = 4,
    vowel = "æ",
    consonant_2 = "t",
    position = "final",
    cons_pos = "t.final"
  ),
  rm.ranef = TRUE,
  rug = FALSE,
  col = "red",
  ylim = c(0.1, 0.6),
  n.grid = 20
)
plot_smooth(
  cq_gam_2,
  "proportion",
  cond = list(
    log_frequency = 4.75,
    vowel = "æ",
    consonant_2 = "t",
    position = "final",
    cons_pos = "t.final"
  ),
  rm.ranef = TRUE,
  rug = FALSE,
  add = TRUE,
  col = "green",
  ylim = c(0.1, 0.6),
  n.grid = 20
)
plot_smooth(
  cq_gam_2,
  "proportion",
  cond = list(
    log_frequency = 5.5,
    vowel = "æ",
    consonant_2 = "t",
    position = "final",
    cons_pos = "t.final"
  ),
  rm.ranef = TRUE,
  rug = FALSE,
  add = TRUE,
  col = "blue",
  ylim = c(0.1, 0.6),
  n.grid = 20
)
```

```{r}
plot_smooth(
  cq_gam_2,
  "proportion",
  cond = list(
    log_frequency = 4.5,
    vowel = "æ",
    position = "medial",
    cons_pos = "t.medial"
  ),
  rm.ranef = TRUE,
  rug = FALSE,
  col = "red",
  ylim = c(0.1, 0.6),
  n.grid = 20
)
plot_smooth(
  cq_gam_2,
  "proportion",
  cond = list(
    log_frequency = 5,
    vowel = "æ",
    position = "medial",
    cons_pos = "t.medial"
  ),
  rm.ranef = TRUE,
  rug = FALSE,
  add = TRUE,
  col = "green",
  ylim = c(0.1, 0.6),
  n.grid = 20
)
plot_smooth(
  cq_gam_2,
  "proportion",
  cond = list(
    log_frequency = 5.5,
    vowel = "æ",
    position = "medial",
    cons_pos = "t.medial"
  ),
  rm.ranef = TRUE,
  rug = FALSE,
  add = TRUE,
  col = "blue",
  ylim = c(0.1, 0.6),
  n.grid = 20
)
```

```{r}
plot_smooth(
  cq_gam_2,
  "proportion",
  cond = list(
    log_frequency = 4,
    vowel = "æ",
    consonant_2 = "k",
    position = "final",
    cons_pos = "k.final"
  ),
  rm.ranef = TRUE,
  rug = FALSE,
  col = "red",
  ylim = c(0.1, 0.6),
  n.grid = 20
)
plot_smooth(
  cq_gam_2,
  "proportion",
  cond = list(
    log_frequency = 4.75,
    vowel = "æ",
    consonant_2 = "k",
    position = "final",
    cons_pos = "k.final"
  ),
  rm.ranef = TRUE,
  rug = FALSE,
  add = TRUE,
  col = "green",
  ylim = c(0.1, 0.6),
  n.grid = 20
)
plot_smooth(
  cq_gam_2,
  "proportion",
  cond = list(
    log_frequency = 5.5,
    vowel = "æ",
    consonant_2 = "k",
    position = "final",
    cons_pos = "k.final"
  ),
  rm.ranef = TRUE,
  rug = FALSE,
  add = TRUE,
  col = "blue",
  ylim = c(0.1, 0.6),
  n.grid = 20
)
```

# LMER

```{r}
cq_lmer <- lmer(
  cq ~
    position *
    consonant_2 *
    log_frequency +
    (1|word),
  data = cq
)
summary(cq_lmer)
```

```{r}
plot(allEffects(cq_lmer))
```

