---
title: "Peaks ratio analysis"
author: "Stefano Coretta and Massimiliano Canzi"
date: "16/03/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../"))
library(tidyverse)
theme_set(theme_minimal())
library(mgcv)
library(tidymv)
library(lmerTest)
library(effects)
options(contrasts = rep("contr.treatment", 2))
```

```{r read-data}
words <- read_csv("./stimuli/words.csv")

degg <- read_csv("./results/tracegram.csv") %>%
  mutate(
    peaks_ratio = maximum / minimum,
    position = ordered(position, levels = c("medial", "final"))
  ) %>%
  left_join(y = words) %>%
  mutate(
    freq_bin = ifelse(
      log_frequency < 4.465,
      "low",
      "high"
    ),
    vowel = as.ordered(vowel),
    consonant_2 = ordered(consonant_2, levels = c("k", "t")),
    cons_pos = interaction(consonant_2, position)
  ) %>%
  mutate_if(is.character, as.factor)
```

# Exploration

```{r}
degg %>%
  ggplot(aes(peaks_ratio)) +
  geom_density()
```

```{r}
degg %>%
  ggplot(aes(peaks_ratio)) +
  geom_density() +
  facet_grid(~ speaker)
```

```{r}
degg %>%
  ggplot(aes(peaks_ratio, fill = position)) +
  geom_density(alpha = 0.3) +
  facet_grid(~ speaker)
```

```{r}
degg %>%
  ggplot(aes(peaks_ratio, fill = position)) +
  geom_density(alpha = 0.3) +
  facet_grid(consonant_2 ~ speaker) +
  geom_rug()
```

```{r}
degg %>%
  ggplot(aes(proportion, peaks_ratio, colour = position)) +
  geom_point(alpha = 0.1) +
  geom_smooth()
```

```{r}
degg %>%
  ggplot(aes(proportion, peaks_ratio, colour = position)) +
  geom_point(alpha = 0.1) +
  geom_smooth() +
  facet_grid(~ consonant_2)
```

```{r}
degg %>%
  filter(peaks_ratio < 0.7) %>%
  ggplot(aes(proportion, peaks_ratio, colour = position)) +
  geom_point(alpha = 0.1) +
  geom_smooth() +
  facet_grid(~ consonant_2)
```

```{r}
degg %>%
  filter(peaks_ratio < 0.7) %>%
  ggplot(aes(consonant_2, peaks_ratio)) +
  geom_violin() +
  geom_boxplot(width = 0.2)
```

```{r}
cq_gam_3 <- bam(
  peaks_ratio ~
    position +
    vowel +
    consonant_2 +
    log_frequency +
    s(proportion) +
    s(proportion, by = position) +
    s(proportion, by = vowel) +
    s(proportion, by = consonant_2) +
    s(proportion, by = cons_pos) +
    ti(proportion, log_frequency) +
    ti(proportion, log_frequency, by = consonant_2) +
    s(proportion, speaker, bs = "fs"),
  data = filter(degg, log_frequency > 3.5),
  method = "ML"
)

summary(cq_gam_3)
```

```{r cq-gam-plot}
fvisgam(
  cq_gam_3,
  view = c("proportion", "log_frequency"),
  cond = list(
    consonant_2 = "t",
    position = "medial", vowel = "æ", cons_pos = "t.medial"),
  rm.ranef = TRUE
)
fvisgam(
  cq_gam_3,
  view = c("proportion", "log_frequency"),
  cond = list(
    consonant_2 = "t",
    position = "final", vowel = "æ", cons_pos = "t.final"),
  rm.ranef = TRUE
)
```

```{r cq-gam-plot}
fvisgam(
  cq_gam_3,
  view = c("proportion", "log_frequency"),
  cond = list(
    consonant_2 = "k",
    position = "medial", vowel = "æ", cons_pos = "t.medial"),
  rm.ranef = TRUE
)
fvisgam(
  cq_gam_3,
  view = c("proportion", "log_frequency"),
  cond = list(
    consonant_2 = "k",
    position = "final", vowel = "æ", cons_pos = "t.final"),
  rm.ranef = TRUE
)
```
